# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"8\n\x08LogEntry\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\"g\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\x05\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x05\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\"6\n\x10RequestVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"\x9e\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\x05\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x05\x12\x15\n\rprev_log_term\x18\x04 \x01(\x05\x12\x1f\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x05\"3\n\x12\x41ppendEntriesReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"!\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"4\n\x0c\x43ommandReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bleader_hint\x18\x02 \x01(\t\"\x1a\n\x0bReadRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"X\n\tReadReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07\x65ntries\x18\x02 \x03(\t\x12\x14\n\x0c\x63ommit_index\x18\x03 \x01(\x05\x12\x13\n\x0bleader_hint\x18\x04 \x01(\t2\x81\x02\n\x0bRaftService\x12?\n\x0bRequestVote\x12\x18.raft.RequestVoteRequest\x1a\x16.raft.RequestVoteReply\x12\x45\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x18.raft.AppendEntriesReply\x12:\n\x0eReceiveCommand\x12\x14.raft.CommandRequest\x1a\x12.raft.CommandReply\x12.\n\x08ReadData\x12\x11.raft.ReadRequest\x1a\x0f.raft.ReadReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGENTRY']._serialized_start=20
  _globals['_LOGENTRY']._serialized_end=76
  _globals['_REQUESTVOTEREQUEST']._serialized_start=78
  _globals['_REQUESTVOTEREQUEST']._serialized_end=181
  _globals['_REQUESTVOTEREPLY']._serialized_start=183
  _globals['_REQUESTVOTEREPLY']._serialized_end=237
  _globals['_APPENDENTRIESREQUEST']._serialized_start=240
  _globals['_APPENDENTRIESREQUEST']._serialized_end=398
  _globals['_APPENDENTRIESREPLY']._serialized_start=400
  _globals['_APPENDENTRIESREPLY']._serialized_end=451
  _globals['_COMMANDREQUEST']._serialized_start=453
  _globals['_COMMANDREQUEST']._serialized_end=486
  _globals['_COMMANDREPLY']._serialized_start=488
  _globals['_COMMANDREPLY']._serialized_end=540
  _globals['_READREQUEST']._serialized_start=542
  _globals['_READREQUEST']._serialized_end=568
  _globals['_READREPLY']._serialized_start=570
  _globals['_READREPLY']._serialized_end=658
  _globals['_RAFTSERVICE']._serialized_start=661
  _globals['_RAFTSERVICE']._serialized_end=918
# @@protoc_insertion_point(module_scope)
